### ISSUE TITLE
Pinata deploy action does not remove old pined

### ISSUE THREAD

**Issue by Lakatoi** [anantaramdas/ipfs-pinata-deploy-action#10]
I use this action to deploy a website but for some time now I've seen that it no longer removes the old pins when running the action. I don't get any error though. This is the code, in case you want to recreate the situation:

```
name: deploysite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master 
      with:
        args: --minify --buildDrafts
    - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      with:
       pin-name: '[My.pin.name]'
       path: './public'
       pinata-api-key: [API Key]
       pinata-secret-api-key: [Secret API Key]
       remove-old: true
```
